/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.chat.panel;

import com.chat.ChatClient;
import com.chat.ChatServer;
import com.chat.Login;
import static com.chat.Login.jPasswordField1;
import static com.chat.Login.jTextField1;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 177
 */
public class Panel extends javax.swing.JPanel {
    public ChatClient cc;
    public ChatServer ca;
    private String url = "jdbc:mysql://localhost:3306/user";
    private String username = "root";
    private String password = "";
    int idpass=0;
    public Panel() {
        initComponents();
       int length = 0;
        int  leng=0;
       
        try {
            int ic=0;
            java.sql.Connection conn = DriverManager.getConnection(url, username, password);
            System.out.println("Database connected!");

            PreparedStatement stmt;
            String query=("SELECT namatampilan FROM account where username = ?");
            stmt = conn.prepareStatement(query);
            stmt.setString(1,Login.jTextField1.getText());
            ResultSet rs = stmt.executeQuery();
            
            String sql = "";
            PreparedStatement pst;
            pst = conn.prepareStatement(sql);
            
            ResultSet srl = pst.executeQuery("SELECT * FROM account");
            
           while (srl.next()) {
                length++;
                if(srl.getString(2).equals(Login.jTextField1.getText())){
                    //namafriend=rs.getString(4);
                    idpass=srl.getInt(1);
                    System.out.println(idpass);
                    ic=1;
                    break;
                }
                else{
                    ic=-1;
                }
            }
            PreparedStatement stm;
            String str="";
            stm = conn.prepareStatement(str);
            ResultSet rss = stm.executeQuery("SELECT * FROM friend where IDAcc = "+ idpass);
            
            DefaultListModel model = new DefaultListModel();
           
            while(rs.next()){
                jLabel1.setText(rs.getString("namatampilan"));
            }
            while(rss.next()){
                leng++;
                model.addElement(rss.getString(2));
            }
            jList1.setModel(model);
            jLabel5.setText("("+leng+")");
            stm.close();
            pst.close();
            stmt.close();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot connect the database!", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 200, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Friends");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jTextField1.setText("jTextField1");
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jLabel3.setText("Search");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Profile Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 50, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/chat/image/icons8_Registration_52px.png"))); // NOI18N
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setPreferredSize(new java.awt.Dimension(32, 32));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int length = 0;
        int idac=0;
        String namafriend="";
        try {
            java.sql.Connection conn = DriverManager.getConnection(url, username, password);
            String query = "";
            PreparedStatement stmt = conn.prepareStatement(query);
            int id = 0;
            ResultSet rs = stmt.executeQuery("SELECT * FROM account");
            
           
            while (rs.next()) {
                length++;
                if(rs.getString(2).equals(jTextField1.getText())) {
                    namafriend=rs.getString(4);
                    id=1;
                    break;
                }
                else{
                    id=-1;
                }
            }
            
            String php = "";
            PreparedStatement post;
            post = conn.prepareStatement(php);
            
            ResultSet srl = post.executeQuery("SELECT * FROM account");
            
           while (srl.next()) {
                length++;
                if(srl.getString(2).equals(Login.jTextField1.getText())){
                    //namafriend=rs.getString(4);
                    idac=srl.getInt(1);
                    System.out.println(idpass);
                }
            }
           
            if(id!=1){
                id=0;
                JFrame f = new JFrame();  
                    JOptionPane.showMessageDialog(f,"Anda Belum Daftar.",
                            "Alert",JOptionPane.WARNING_MESSAGE);
            }
            else{
                String sql = "Insert into friend values(?,?,?)";
                PreparedStatement pst = conn.prepareStatement(sql);
                int idd = 0;
            
                pst.setInt(1, idd);
                pst.setString(2, namafriend);
                pst.setInt(3, idac);
                pst.execute();
                
                pst.close();
            }    
            stmt.close();
            conn.close();
            post.close();
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot connect the database!", e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JTextField jTextField1 = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables
}
